### ISSUE TITLE
No ammo !

### ISSUE THREAD

**Issue by Bonjemus** [AlmightyLks/CustomLoadout#2]
Classes who get inventory cleared loses all their ammos, could you change that ?

**Comment by AlmightyLks** [comment]
Noted, will take a look at it soon.

**Comment by AlmightyLks** [comment]
Fixed and made the the ammo configurable, [Release 1.1.2](https://github.com/AlmightyLks/CustomLoadout/releases/tag/v1.1.2)

**Comment by Bonjemus** [comment]
Thanks !

**Comment by Bonjemus** [comment]
Will this version delete alle the configs ?

**Comment by AlmightyLks** [comment]
YAML parsing (and many other config-parsers) works as following:
- If a config with the same name ("CustomLoadout") already exists, it will recognize it and parse its content. Problem with that:
    - It will not recognize that parts of the configs are missing, due to a new update - Because potentially it could be intentionally removed, because it is unwanted.

What I recommend for such updates:
- Copy and paste your plugin configs into notepad or whatever
- Start the server / reload the configs and let it regenerate the new default configs
- Replace the old parts of the configs from what you temporarily put into notepad or whatever

**Comment by Bonjemus** [comment]
Ok, thanks for the tip.
Have a nice day.
